# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20160815_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemameta',
            name='survey',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='rest_api.Survey'),
            preserve_default=False,
        ),
    ]
