language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=params.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

#before_script:
#  - python manage.py collectstatic --noinput

script:
  - cd qBuilder
  - python manage.py test
