language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.4.1
  - npm install -g npm@3
  - npm install

before_script:
  - psql -c 'create user "eq-author" createdb;' -U postgres
  
script:
  - npm run test
  - cd qBuilder
  - python manage.py test

notifications:
  slack: digitaleq:LDxJXRGeVmg3PpdUhp90eY3Z
