language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
  - . $HOME/.nvm/nvm.sh
  - nvm install v5.2.0
  - npm install

before_script:
  - psql -c 'create user "eq-author" createdb;' -U postgres
  - npm run compile

script:
  - cd qBuilder
  - python manage.py test
