language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create user `eq-author` with password \'password\';' -U postgres
  - psql -c 'create database qBuilder;' -U postgres
  - psql -c 'grant all on database qBuilder to `eq-author`;' -U postgres
#  - python manage.py collectstatic --noinput

script:
  - cd qBuilder
  - python manage.py test
