language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c 'create user eq_author;' -U postgres
  - psql -c 'create database eq-author;' -U eq_author
#  - python manage.py collectstatic --noinput

script:
  - cd qBuilder
  - python manage.py test
