# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaMeta',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'ordering': ('created', 'eq_id'),
            },
        ),
    ]
