# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 11:07
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os


def create_super_user(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    superuser = User.objects.create(
        username=os.getenv('EQ_AUTHOR_ADMIN_USERNAME'),
        email=os.getenv('EQ_AUTHOR_ADMIN_EMAIL'),
        password=make_password(os.getenv('EQ_AUTHOR_ADMIN_PASSWORD')),
        is_superuser=True,
        is_staff=True,
        first_name=os.getenv('EQ_AUTHOR_ADMIN_FIRSTNAME'),
        last_name=os.getenv('EQ_AUTHOR_ADMIN_LASTNAME')
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
